### ISSUE TITLE
Installation not working on Mac

### ISSUE THREAD

**Issue by i11v** [sourcemint/sm-npm#15] opened 2012-12-11 08:36 UTC
ERROR: Could not find `sm` on your PATH (/usr/local/Cellar/node/0.8.15/bin:/usr/local/Cellar/node/0.8.15/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/share/npm/lib/node_modules/sm/node_modules/.bin:/usr/local/share/npm/lib/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin)! NPM should have installed it.
npm ERR! sm@0.2.11 postinstall: `node ./scripts/postinstall.js`
npm ERR! `sh "-c" "node ./scripts/postinstall.js"` failed with 1
npm ERR! 
npm ERR! Failed at the sm@0.2.11 postinstall script.
npm ERR! This is most likely a problem with the sm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sm
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "/usr/local/Cellar/node/0.8.15/bin/node" "/usr/local/bin/npm" "install" "-g" "sm"
npm ERR! cwd /Users/R2D2
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE

More you can see at https://raw.github.com/gist/4256961/c662e6f03d5ec47799b5a4a79dbccbb0454734c1/npm-sm-installation.log

**Comment by cadorn** [comment] 2012-12-11 19:33
The problem is in the `postinstall` script. This will be fixed in `sm@0.3`. In the meantime you can clone this repo, remove the postinstall script in package.json and then run npm install. Then put the `./bin/sm` command on your `PATH` yourself.

**Closed as completed by cadorn** 2012-12-11 19:33 UTC
